version: '3.8'

services:
  db:
    image: postgres:15
    container_name: sukut_postgres
    environment:
      POSTGRES_DB: sukut_forecasting
      POSTGRES_USER: sukut_user
      POSTGRES_PASSWORD: sukut_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sukut_network

  redis:
    image: redis:7-alpine
    container_name: sukut_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sukut_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sukut_backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://sukut_user:sukut_password@db:5432/sukut_forecasting
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    networks:
      - sukut_network
    profiles:
      - full

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sukut_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - sukut_network
    profiles:
      - full

volumes:
  postgres_data:
  redis_data:

networks:
  sukut_network:
    driver: bridge